apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3010
    nodePort: 30010 # Choose any available port in the range 30000-32767
