apiVersion: apps/v1
kind: Deployment
metadata:
  name: progression-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progression
  template:
    metadata:
      labels:
        app: progression
    spec:
      containers:
      - name: progression
        image: progression-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
