apiVersion: v1
kind: Service
metadata:
  name: progression-service
spec:
  type: NodePort
  selector:
    app: progression
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30002 # Choose any available port in the range 30000-32767
