apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: NodePort
  selector:
    app: course
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001 # Choose any available port in the range 30000-32767
