apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
    nodePort: 30004 # Choose any available port in the range 30000-32767
